services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    networks:
      - home-intranet-nginx
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: ${WEB_PASSWORD}
      VIRTUAL_HOST: "pihole.homeintranet.local"
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
