services:
  pihole-tailscale:
    image: tailscale/tailscale:latest
    container_name: pihole-tailscale
    hostname: pihole
    healthcheck:
      test: ["CMD", "tailscale", "status", "--peers=false"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - TS_AUTHKEY=${TAILSCALE_OAUTH_KEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:intranet --reset
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=pihole.json
    volumes:
      - pihole-tailscale:/var/lib/tailscale
      - ./pihole.json:/pihole.json
      - ./resolv.conf:/etc/resolv.conf # Manually configuring upstream DNS
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: service:pihole-tailscale
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: ${PI_HOLE_WEB_PASSWORD}
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - net_admin
    depends_on:
      pihole-tailscale:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pihole-tailscale:
    driver: local
